services:
  spend-less-node-red:
    build:
      context: node-red
    volumes:
      - ./node-red/settings.js:/data/settings.js
      - spend-less-node-red-data:/data
    ports:
      - 1880:1880

volumes:
  spend-less-node-red-data:
